Jenkinsfile: Updates build library version
Error: git branch -v --no-abbrev --contains 4c739f9b247f7147a1ec74ada643f48f65e7b864 # timeout=10
Could not find a branch containing commit 4c739f9b247f7147a1ec74ada643f48f65e7b864
ERROR: No version 4c739f9 found for library github.com/triologygmbh/jenkinsfile